version: 0.2

phases:
  pre_build:
    commands:
      - cd supply-check
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./supply-check/build